# Generated by Django 5.0.6 on 2024-05-30 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=255)),
                ('descricao', models.TextField(default='', max_length=1000)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('marca', models.CharField(default='', max_length=255)),
                ('categoria', models.CharField(choices=[('Eletronicos', 'Eletronicos'), ('Comidas', 'Comida'), ('CASA', 'Casa'), ('COZINHA', 'Cozinha'), ('ROUPAS', 'Roupas'), ('ESPORTE', 'Esporte'), ('BRINQUEDOS', 'Brinquedos'), ('LIVROS', 'Livros')], max_length=30)),
                ('avaliacoes', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('estoque', models.IntegerField(default=0)),
                ('criadoEm', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
