# Generated by Django 5.0.6 on 2024-05-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('Eletronicos', 'Eletronicos'), ('Comidas', 'Comida'), ('Casa', 'Casa'), ('Cozinha', 'Cozinha'), ('Roupas', 'Roupas'), ('Esporte', 'Esporte'), ('Brinquedos', 'Brinquedos'), ('Livros', 'Livros')], max_length=30),
        ),
    ]
